# Version
version: '3.1'

# Setup
services:
  # PHP
  php:
    depends_on:
      - db
    image: dockerphp:1.0
    restart: always
    ports:
      - 5000:80
    volumes:
      - ./development:/var/www/html
    networks:
      - dockerphp

  # PHPMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 5050:80
    environment:
      PMA_HOST: db
    networks:
      - dockerphp

  # MySQL
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./dockerphp_db:/var/lib/mysql
    environment:
      MYSQL_USERNAME: lugasdev
      MYSQL_DATABASE: dockerphp
      MYSQL_PASSWORD: lugasdev
      MYSQL_ROOT_PASSWORD: lugasdev
    networks:
      - dockerphp
  
  composer:
    image: composer:2.2.1
    depends_on:
      - php
    networks:
      - dockerphp
    

# Volumes
volumes:
  dockerphp_db:
  dockerphp_uploads:

networks:
  dockerphp: